### ISSUE TITLE
Explore data: Detailed cards and top locations don't always respond to year slider

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#391]
I'm in Chrome, and some things are not responding to the year slider changing. It works some of the time. I also experienced the Native American card working while the nationwide card did not update the year. The summary cards and the nationwide revenue summary seem to be responding to the year slider properly.

![image](https://user-images.githubusercontent.com/30806839/81190600-0b86e180-8f86-11ea-8d4f-0e6e4538ed28.png)

![image](https://user-images.githubusercontent.com/30806839/81190903-66203d80-8f86-11ea-8f1c-e8a805965269.png)

**Comment by jennmalcolm** [comment]
Just tested again, and it worked a few times, but then the problem appeared again. ![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/2bae31ba-1ee5-437a-82b8-e491ae78efc5)

**Comment by mojobnichols** [comment]
Fixed and commited to preview

https://421-422-423-databasechanges.app.cloud.gov/explore/

PR:

https://github.com/ONRR/nrrd/pull/443

**Comment by mojobnichols** [comment]
I must of being trying to put a different one into review.   I didn't fix this one - yet.  I'd like to get the others merged to dev first. 

I'm changing the estimate to 5 because of the complexity  of it.

**Comment by jennmalcolm** [comment]
Really @mojobnichols with my testing, this was working in #443.

**Comment by mojobnichols** [comment]
@mcharg and @jennmalcolm 

I can't reproduce except nation wide summary was using Monthly so anyting prior to 2008 wasn't showing up.  I just corrected that. .. can you review in: 

https://github.com/ONRR/nrrd/pull/481

**Comment by mcharg** [comment]
Nationwide summary still isn't showing up.
![image](https://user-images.githubusercontent.com/38465926/83181839-73e36180-a0f3-11ea-93a5-5d4b52a4ee00.png)
